version: '3.6'

services:
    mysql1:
        container_name: mysql1
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=9fe0f919743cd92b
            - TZ=US/Eastern
        ports:
            - '3306:3306'
        expose:
            - '3306'
        networks:
            - app-network
        volumes:
            -   type: bind
                source: ./database
                target: /docker-entrypoint-initdb.d

    api:
        container_name: api
        restart: always
        build: ./api/.
        volumes:
            - ./api:/usr/src/app
        depends_on:
            - mysql1
        ports:
            - "8081:8081"
        expose:
            - "8081"
        networks:
            - app-network

    python1:
        container_name: python1
        build: ./python1/.
        ports:
            - "8079:8079"
        expose:
            - "8079"
        volumes:
            - ./python1/:/usr/src/app
        depends_on:
            - mysql1
            - api
        links:
            - mysql1
            - api
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
